# Generated by Django 5.2.6 on 2026-02-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_is_flash_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_hover',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
