# Generated by Django 5.2.6 on 2026-02-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_best_seller',
        ),
        migrations.AddField(
            model_name='product',
            name='flash_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
